services:
  - type: web
    name: blog-generator
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn blog_generator_django.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false